### ISSUE TITLE
1.20.1 incompatible mod

### ISSUE THREAD

**Issue by rtxyd** [fzzyhmstrs/fc#3]
Just for notice, 
not compatible with mermod [https://modrinth.com/mod/mermod](url)
Will crash when create new world.
Modlist:
fabric-api-0.92.1+1.20.1
fabric-language-kotlin-1.10.19+kotlin.1.9.23
fzzy_core-0.5.0+1.20.1
trinkets-3.7.2
mermod-fabric-2.41.
  **But if only delete trinkets, will not crash.**
Crash report:
[crash-2024-04-29_00.22.31-client.txt](https://github.com/fzzyhmstrs/fc/files/15142795/crash-2024-04-29_00.22.31-client.txt)

**Comment by fzzyhmstrs** [comment]
Newest version just released on CF/Modrinth should fix this issue
